#define WRITEBYTE(WORD,STARTBIT,BYTE)\
  WORD=(WORD&(u32)~0xff<<STARTBIT)|(BYTE<<STARTBIT)
#define READBIT(WORD,BIT)  ((WORD>>BIT)&1)
#define WRITEBIT(WORD,STARTBIT,BITLEVEL)\
  WORD=(WORD&~(1<<BIT))|(BITLEVEL<<BIT)
#define READWRITEBIT(WORD,DBIT,SBIT)\
  WORD=((WORD&~(1<<DBIT))|(((WORD>>SBIT)&1)<<DBIT))
#define READWRITEBIT2(WORD,DBIT,SWORD,SBIT)\
 WORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#define WRITENIBBLE(WORD,STARTBIT,NIBBLE)\
        WORD=(WORD&(u32)~0XF<<STARTBIT)|(NIBBLE<<STARTBIT)
#define READNIBBLE(WORD,SBIT)   ((WORD>>SBIT)&15)
